import Link from "next/link";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { Hero } from "@/components/Hero";
import { Reveal } from "@/components/Reveal";
import { menuItems } from "@/data/menu";

export default function Home() {
  const featured = menuItems.filter((item) => ["espresso", "croissant", "tart"].includes(item.id));
  return <main><Hero /><section className="intro section-pad"><div className="eyebrow">01 / Our coffee</div><div className="intro-grid"><h2 className="display display-lg">Good coffee takes its time.</h2><div className="intro-copy"><p>We roast with curiosity, brew with patience, and make space for the small rituals that turn an ordinary day into a good one.</p><Link className="text-link" href="/about">Meet the people <ArrowUpRight size={16} /></Link></div></div></section><section className="feature-strip"><div className="feature-image image-coffee" role="img" aria-label="A fresh coffee on a wooden table" /><div className="feature-note"><span className="eyebrow">Roasted in small batches</span><span className="display display-md">From first light<br />to last sip.</span><ArrowDownRight size={34} strokeWidth={1} /></div></section><section className="section-pad menu-preview"><div className="section-head"><div><span className="eyebrow">02 / From the counter</span><h2 className="display display-md">A little something<br />for every mood.</h2></div><Link className="circle-link" href="/menu" aria-label="View the full menu"><ArrowUpRight size={22} /></Link></div><div className="product-grid">{featured.map((item) => <article className="product-tile" key={item.id}><div className="product-image" style={{ backgroundImage: `url(${item.image})` }} /><div className="product-meta"><div><h3>{item.name}</h3><p>{item.description}</p></div><span>R{item.price}</span></div></article>)}</div></section><Reveal className="join-section"><div className="eyebrow">03 / Come by</div><h2 className="display display-xl">Join us for<br /><em>a slow cup.</em></h2><Link className="button button-light" href="/contact">Find your way here <ArrowUpRight size={17} /></Link></Reveal></main>;
}
